vich_uploader:
    db_driver: orm

    mappings:
        album_images:
            uri_prefix: '%album_images%'
            upload_destination: '%kernel.project_dir%/public%album_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
            inject_on_load: true
        gallery_images:
            uri_prefix: '%gallery_images%'
            upload_destination: '%kernel.project_dir%/public%gallery_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
